version: '3.8'

services:
  catalog_service:
    # container_name: catalog-service
    image: catalog_service
    build: ./CatalogService

    ports:
      - "5001-5002:5002"
    deploy:
      replicas: 2
    env_file: config_env

  order_service:
    image: order_service
    build: 
      context: ./OrderService
      dockerfile: deployments/Dockerfile
    ports:
      - "5007:5007"
    env_file: config_env

  front_end_service:
    image: front_end_service
    build: 
      context: ./FrontendService
      dockerfile: deployments/Dockerfile
    ports:
      - "5004:5004"
    env_file: config_env
