version: '3.8'

services:
  catalog-service-1:
    container_name: catalog-service-1
    build: ./CatalogService

    ports:
      - "5001:5002"
  
  catalog-service-2:
    container_name: catalog-service-2
    build: ./CatalogService

    ports:
      - "5002:5002"
  
  order-service:
    container_name: order-service
    build: 
      context: ./OrderService
      dockerfile: deployments/Dockerfile
    ports:
      - "5007:5007"
    env_file: config_env

  front-end-service:
    container_name: front-end-service
    build: 
      context: ./FrontendService
      dockerfile: deployments/Dockerfile
    ports:
      - "5004:5004"
    env_file: config_env
